/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Administrador
 */
public class app extends javax.swing.JFrame {
    
    DefaultTableModel datamodel = new DefaultTableModel();

    /**
     * Creates new form app
     */
    public app() throws SQLException {
        setUndecorated(true);
        initComponents();
        
        Image icono = Toolkit.getDefaultToolkit().getImage(
				"src/img/logo_adherencia.png");
        this.setIconImage(icono);
        
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        
        String tituloTabla[] = new String[]{"Fecha","Ingreso Planificado","Hora de conexion","Egreso Planificado","Hora de desconexion"};
        datamodel.setColumnIdentifiers(tituloTabla);
        tbl.setModel(datamodel);
        cargarData();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hour2 = new javax.swing.JTextField();
        hour1 = new javax.swing.JTextField();
        hour3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        retardos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tiempo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Adobe Devanagari", 3, 12)); // NOI18N
        jLabel1.setText("<html><u>Horas en el turno programado</u></html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 180, 30));

        jLabel2.setFont(new java.awt.Font("Adobe Devanagari", 3, 12)); // NOI18N
        jLabel2.setText("<html><u>Horas de logeo mes actual</u></html>");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 30));

        hour2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        hour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hour2ActionPerformed(evt);
            }
        });
        jPanel1.add(hour2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 75, 30));

        hour1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        hour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hour1ActionPerformed(evt);
            }
        });
        jPanel1.add(hour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 75, 30));

        hour3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(hour3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 75, 30));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 359, 747, 208));

        jLabel4.setFont(new java.awt.Font("Adobe Devanagari", 3, 12)); // NOI18N
        jLabel4.setText("<html><u>Horas logeo Planificadas</u></html>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cerrar");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel3KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 58, -1));

        name.setFont(new java.awt.Font("Adobe Devanagari", 3, 12)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 23, 229, 90));

        jLabel5.setFont(new java.awt.Font("Adobe Devanagari", 3, 12)); // NOI18N
        jLabel5.setText("<html><u>Tiempo que debes en total</u></html>");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, 30));

        retardos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        retardos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retardosActionPerformed(evt);
            }
        });
        jPanel1.add(retardos, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 75, 30));

        jLabel6.setFont(new java.awt.Font("Adobe Devanagari", 3, 12)); // NOI18N
        jLabel6.setText("<html><u>Cantidad de retardos</u></html>");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, 30));

        tiempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });
        jPanel1.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 75, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("CONTROL DE ADHERENCIA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 270, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("<html>A continuación podrás ver cuantas horas tienes pendientes <br> de logueo y adicional cuantos retardos tienes en el mes.</html>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_adherencia.jpg"))); // NOI18N
        fondo.setText("jLabel9");
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 830, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 820, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hour1ActionPerformed

    private void hour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hour2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hour2ActionPerformed

    private void jLabel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyPressed
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3KeyPressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void retardosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retardosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retardosActionPerformed

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new app().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField hour1;
    private javax.swing.JTextField hour2;
    private javax.swing.JTextField hour3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel name;
    private javax.swing.JTextField retardos;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField tiempo;
    // End of variables declaration//GEN-END:variables
    private Object ax = System.getenv("username");
    private String usuario = String.valueOf(ax);
     
    
    
    public void cargarData() throws SQLException{
        
        Statement std = conexionsqlserver.getConnection().createStatement();
        
        ResultSet rs1 =std.executeQuery("SELECT Agente,leg,TIEMPO_LOGUEO_REAL,horas_planificadas,horas_turno_programado,LLegadas_tarde FROM dbo.Agrupacion_mensual_Adherencia WHERE Windows ='" +usuario+"'  ");
        
        if(rs1.next()){
            
            name.setText("<html>"+rs1.getString("Agente")+"<br>Formacion y Calidad"+"<br>"+rs1.getString("leg"));
            hour1.setText(rs1.getString("TIEMPO_LOGUEO_REAL"));
            hour2.setText(rs1.getString("horas_planificadas"));
            hour3.setText(rs1.getString("horas_turno_programado"));
            retardos.setText(rs1.getString("LLegadas_tarde"));
            double logeo,planificado,tiempo_total;
            logeo=rs1.getDouble("TIEMPO_LOGUEO_REAL");
            planificado=rs1.getDouble("horas_planificadas");
            tiempo_total=logeo-planificado;
            tiempo.setText(""+tiempo_total);
            
            
        }
        
        
         ResultSet rs =std.executeQuery("SELECT *  FROM dbo.Agrupacion_mensual_turnos WHERE Windows ='" +usuario+"'  ");
    
        while(rs.next()){
            
            datamodel.addRow(new Object[]{
                
                rs.getString(1),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6)
            
                
            });
            
        }
        
    }
}
