
import com.placeholder.PlaceHolder;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.border.EmptyBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felipe
 */
public class encuesta extends JFrame  {
     
    
    /**
     * Creates new form encuesta
     */
    public encuesta() throws SQLException {
        
            
        setUndecorated(true);
        initComponents();
        Image icono = Toolkit.getDefaultToolkit().getImage(
				"src/img/logo_adherencia.png");
        this.setIconImage(icono);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        cargarEncuesta();
        
        
       
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        p1r1 = new javax.swing.JCheckBox();
        p1r2 = new javax.swing.JCheckBox();
        p1r3 = new javax.swing.JCheckBox();
        p1r4 = new javax.swing.JCheckBox();
        p1r5 = new javax.swing.JCheckBox();
        p1r6 = new javax.swing.JCheckBox();
        p2 = new javax.swing.JLabel();
        p2r1 = new javax.swing.JCheckBox();
        p2r2 = new javax.swing.JCheckBox();
        p2r3 = new javax.swing.JCheckBox();
        p2r4 = new javax.swing.JCheckBox();
        p2r5 = new javax.swing.JCheckBox();
        p2r6 = new javax.swing.JCheckBox();
        Enviar = new javax.swing.JButton();
        p3 = new javax.swing.JLabel();
        p3r1 = new javax.swing.JCheckBox();
        p3r2 = new javax.swing.JCheckBox();
        p3r3 = new javax.swing.JCheckBox();
        p3r4 = new javax.swing.JCheckBox();
        p3r5 = new javax.swing.JCheckBox();
        p3r6 = new javax.swing.JCheckBox();
        p4 = new javax.swing.JLabel();
        p4r1 = new javax.swing.JCheckBox();
        p4r2 = new javax.swing.JCheckBox();
        p4r3 = new javax.swing.JCheckBox();
        p4r4 = new javax.swing.JCheckBox();
        p4r5 = new javax.swing.JCheckBox();
        p4r6 = new javax.swing.JCheckBox();
        p5r1 = new javax.swing.JCheckBox();
        p5r2 = new javax.swing.JCheckBox();
        p5r3 = new javax.swing.JCheckBox();
        p5r4 = new javax.swing.JCheckBox();
        p5r5 = new javax.swing.JCheckBox();
        p5r6 = new javax.swing.JCheckBox();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p6r1 = new javax.swing.JCheckBox();
        p6r2 = new javax.swing.JCheckBox();
        p6r3 = new javax.swing.JCheckBox();
        p6r4 = new javax.swing.JCheckBox();
        p6r5 = new javax.swing.JCheckBox();
        p6r6 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentario = new javax.swing.JTextArea();
        p7 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 479, 40));

        img.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_jazzplat2.jpg"))); // NOI18N
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMouseClicked(evt);
            }
        });
        img.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imgKeyPressed(evt);
            }
        });
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 190, 50));

        buttonGroup1.add(p1r1);
        jPanel1.add(p1r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 96, -1, -1));

        buttonGroup1.add(p1r2);
        jPanel1.add(p1r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 119, -1, -1));

        buttonGroup1.add(p1r3);
        jPanel1.add(p1r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 142, -1, -1));

        buttonGroup1.add(p1r4);
        jPanel1.add(p1r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 165, -1, -1));

        buttonGroup1.add(p1r5);
        jPanel1.add(p1r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 188, -1, -1));

        buttonGroup1.add(p1r6);
        jPanel1.add(p1r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 211, -1, -1));

        p2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 580, 40));

        buttonGroup2.add(p2r1);
        jPanel1.add(p2r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 289, -1, -1));

        buttonGroup2.add(p2r2);
        jPanel1.add(p2r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 312, -1, -1));

        buttonGroup2.add(p2r3);
        jPanel1.add(p2r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 335, -1, -1));

        buttonGroup2.add(p2r4);
        jPanel1.add(p2r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 358, -1, -1));

        buttonGroup2.add(p2r5);
        jPanel1.add(p2r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 381, -1, -1));

        buttonGroup2.add(p2r6);
        jPanel1.add(p2r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 404, -1, -1));

        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        jPanel1.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, -1, -1));

        p3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 580, 40));

        buttonGroup3.add(p3r1);
        jPanel1.add(p3r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        buttonGroup3.add(p3r2);
        jPanel1.add(p3r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        buttonGroup3.add(p3r3);
        jPanel1.add(p3r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        buttonGroup3.add(p3r4);
        jPanel1.add(p3r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        buttonGroup3.add(p3r5);
        jPanel1.add(p3r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        buttonGroup3.add(p3r6);
        jPanel1.add(p3r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        p4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 610, 40));

        buttonGroup4.add(p4r1);
        jPanel1.add(p4r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        buttonGroup4.add(p4r2);
        jPanel1.add(p4r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        buttonGroup4.add(p4r3);
        jPanel1.add(p4r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        buttonGroup4.add(p4r4);
        jPanel1.add(p4r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        buttonGroup4.add(p4r5);
        jPanel1.add(p4r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        buttonGroup4.add(p4r6);
        jPanel1.add(p4r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        buttonGroup5.add(p5r1);
        jPanel1.add(p5r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));

        buttonGroup5.add(p5r2);
        jPanel1.add(p5r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, -1));

        buttonGroup5.add(p5r3);
        jPanel1.add(p5r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        buttonGroup5.add(p5r4);
        jPanel1.add(p5r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));

        buttonGroup5.add(p5r5);
        jPanel1.add(p5r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        buttonGroup5.add(p5r6);
        jPanel1.add(p5r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        p5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 610, 40));

        p6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 610, 40));

        buttonGroup6.add(p6r1);
        jPanel1.add(p6r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        buttonGroup6.add(p6r2);
        jPanel1.add(p6r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        buttonGroup6.add(p6r3);
        jPanel1.add(p6r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, -1, -1));

        buttonGroup6.add(p6r4);
        jPanel1.add(p6r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, -1, -1));

        buttonGroup6.add(p6r5);
        jPanel1.add(p6r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, -1, -1));

        buttonGroup6.add(p6r6);
        jPanel1.add(p6r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, -1, -1));

        comentario.setColumns(20);
        comentario.setRows(5);
        comentario.setToolTipText("ghgh");
        comentario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comentarioKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(comentario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 390, 40));

        p7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        p7.setText("Escribe tu opinion ");
        jPanel1.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 400, 20));

        p1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 580, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
    
         if(p1r1.isSelected()){
            c1=1;
            r1=p1r1.getText().toString();
     
         }
         if(p1r2.isSelected()){
            c1=1;  
            r1=p1r2.getText().toString();
         }
         if(p1r3.isSelected()){
            c1=1;
            r1=p1r3.getText().toString();
         }
         if(p1r4.isSelected()){
            c1=1;
            r1=p1r4.getText().toString();
         }
         if(p1r5.isSelected()){
            c1=1;
            r1=p1r5.getText().toString();
         }
         if(p1r6.isSelected()){
            c1=1;
            r1=p1r6.getText().toString();
         }
         
         if(p2r1.isSelected()){
            c2=1;
            r2=p2r1.getText().toString();
         }
         if(p2r2.isSelected()){
            c2=1;  
            r2=p2r2.getText().toString();
         }
         if(p2r3.isSelected()){
            c2=1;
            r2=p2r3.getText().toString();
         }
         if(p2r4.isSelected()){
            c2=1;
            r2=p2r4.getText().toString();;
         }
         if(p2r5.isSelected()){
            c2=1;
            r2=p2r5.getText().toString();;
         }
         if(p2r6.isSelected()){
            c2=1;
            r2=p2r6.getText().toString();;
         }
        
 
           if(p3r1.isSelected()){
            c3=1;
            r3=p3r1.getText().toString();;
         }
         if(p3r2.isSelected()){
            c3=1;  
            r3=p3r2.getText().toString();;
         }
         if(p3r3.isSelected()){
            c3=1;
            r3=p3r3.getText().toString();;
         }
         if(p3r4.isSelected()){
            c3=1;
            r3=p3r4.getText().toString();;
         }
         if(p3r5.isSelected()){
            c3=1;
            r3=p3r5.getText().toString();;
         }
         if(p3r6.isSelected()){
            c3=1;
            r3=p3r6.getText().toString();;
         }
         
         if(p4r1.isSelected()){
            c4=1;
            r4=p4r1.getText().toString();;
         }
         if(p4r2.isSelected()){
            c4=1;  
            r4=p4r2.getText().toString();;
         }
         if(p4r3.isSelected()){
            c4=1;
            r4=p4r3.getText().toString();;
         }
         if(p4r4.isSelected()){
            c4=1;
            r4=p4r4.getText().toString();;
         }
         if(p4r5.isSelected()){
            c4=1;
            r4=p4r5.getText().toString();;
         }
         if(p4r6.isSelected()){
            c4=1;
            r4=p4r6.getText().toString();;
         }
         
          if(p5r1.isSelected()){
            c5=1;
            r5=p5r1.getText().toString();;
         }
         if(p5r2.isSelected()){
            c5=1;  
            r5=p5r2.getText().toString();;
         }
         if(p5r3.isSelected()){
            c5=1;
            r5=p5r3.getText().toString();;
         }
         if(p5r4.isSelected()){
            c5=1;
            r5=p5r4.getText().toString();;
         }
         if(p5r5.isSelected()){
            c5=1;
            r5=p5r5.getText().toString();;
         }
         if(p5r6.isSelected()){
            c5=1;
            r5=p5r6.getText().toString();;
         }
         
         if(p6r1.isSelected()){
            c6=1;
            r6=p6r1.getText().toString();;
         }
         if(p6r2.isSelected()){
            c6=1;  
            r6=p6r2.getText().toString();;
         }
         if(p6r3.isSelected()){
            c6=1;
            r6=p6r3.getText().toString();;
         }
         if(p6r4.isSelected()){
            c6=1;
            r6=p6r4.getText().toString();;
         }
         if(p6r5.isSelected()){
            c6=1;
            r6=p6r5.getText().toString();;
         }
         if(p6r6.isSelected()){
            c6=1;
            r6=p6r6.getText().toString();;
         }
         
     
              if(comentario.getText().equals("") ){         
        }else{
             c7=1;
             r7=comentario.getText().toString();;
              }
       
         sumcres=c1+c2+c3+c4+c5+c6+c7; 
         if(sumcres==contador){
            try {
                Statement std;
                std = conexion.ConnectDB().createStatement();
                
                if(c1==1){
                    std.executeUpdate("INSERT INTO respuestas_enc(Sector,Cargo,Personal,User_Win,id_pregunta,Rta_User) VALUES ('"+sector+"','"+cargo+"','"+personal+"','"+usuario+"','1','"+r1+"') ");
                  
                    
                }
                if(c2==1){
                    std.executeUpdate("INSERT INTO respuestas_enc(Sector,Cargo,Personal,User_Win,id_pregunta,Rta_User) VALUES ('"+sector+"','"+cargo+"','"+personal+"','"+usuario+"','2','"+r2+"') ");
                    
                    
                }
                if(c3==1){
                    std.executeUpdate("INSERT INTO respuestas_enc(Sector,Cargo,Personal,User_Win,id_pregunta,Rta_User) VALUES ('"+sector+"','"+cargo+"','"+personal+"','"+usuario+"','3','"+r3+"') ");
                  
                    
                }
                if(c4==1){
                    std.executeUpdate("INSERT INTO respuestas_enc(Sector,Cargo,Personal,User_Win,id_pregunta,Rta_User) VALUES ('"+sector+"','"+cargo+"','"+personal+"','"+usuario+"','4','"+r4+"') ");
            
                    
                }
                if(c5==1){
                    std.executeUpdate("INSERT INTO respuestas_enc(Sector,Cargo,Personal,User_Win,id_pregunta,Rta_User) VALUES ('"+sector+"','"+cargo+"','"+personal+"','"+usuario+"','5','"+r5+"') ");
                   
                    
                }
                if(c6==1){
                    std.executeUpdate("INSERT INTO respuestas_enc(Sector,Cargo,Personal,User_Win,id_pregunta,Rta_User) VALUES ('"+sector+"','"+cargo+"','"+personal+"','"+usuario+"','6','"+r6+"') ");
                
                    
                }
                if(c7==1){
                    std.executeUpdate("INSERT INTO respuestas_enc(Sector,Cargo,Personal,User_Win,id_pregunta,Rta_User) VALUES ('"+sector+"','"+cargo+"','"+personal+"','"+usuario+"','7','"+r7+"') ");
                    
                    
                }
                JOptionPane.showMessageDialog(null, "Tus respuestas han sido enviadas .");
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(encuesta.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"error"+ex);
            }    
               
             
         }else{
             JOptionPane.showMessageDialog(null, "Por favor , responde todas las preguntas "); 
         }
         
            
         
    
        // TODO add your handling code here:
    }//GEN-LAST:event_EnviarActionPerformed

    private void comentarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comentarioKeyTyped
           
       int limite_comentario=200;
      if (comentario.getText().length() >= limite_comentario)
      {
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Maximo 200 caracteres .");
      }

					

			
    
    }//GEN-LAST:event_comentarioKeyTyped

    private void imgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imgKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_imgKeyPressed

    private void imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseClicked
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_imgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        int time=0;
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                try {
                   new encuesta().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(encuesta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextArea comentario;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel p1;
    private javax.swing.JCheckBox p1r1;
    private javax.swing.JCheckBox p1r2;
    private javax.swing.JCheckBox p1r3;
    private javax.swing.JCheckBox p1r4;
    private javax.swing.JCheckBox p1r5;
    private javax.swing.JCheckBox p1r6;
    private javax.swing.JLabel p2;
    private javax.swing.JCheckBox p2r1;
    private javax.swing.JCheckBox p2r2;
    private javax.swing.JCheckBox p2r3;
    private javax.swing.JCheckBox p2r4;
    private javax.swing.JCheckBox p2r5;
    private javax.swing.JCheckBox p2r6;
    private javax.swing.JLabel p3;
    private javax.swing.JCheckBox p3r1;
    private javax.swing.JCheckBox p3r2;
    private javax.swing.JCheckBox p3r3;
    private javax.swing.JCheckBox p3r4;
    private javax.swing.JCheckBox p3r5;
    private javax.swing.JCheckBox p3r6;
    private javax.swing.JLabel p4;
    private javax.swing.JCheckBox p4r1;
    private javax.swing.JCheckBox p4r2;
    private javax.swing.JCheckBox p4r3;
    private javax.swing.JCheckBox p4r4;
    private javax.swing.JCheckBox p4r5;
    private javax.swing.JCheckBox p4r6;
    private javax.swing.JLabel p5;
    private javax.swing.JCheckBox p5r1;
    private javax.swing.JCheckBox p5r2;
    private javax.swing.JCheckBox p5r3;
    private javax.swing.JCheckBox p5r4;
    private javax.swing.JCheckBox p5r5;
    private javax.swing.JCheckBox p5r6;
    private javax.swing.JLabel p6;
    private javax.swing.JCheckBox p6r1;
    private javax.swing.JCheckBox p6r2;
    private javax.swing.JCheckBox p6r3;
    private javax.swing.JCheckBox p6r4;
    private javax.swing.JCheckBox p6r5;
    private javax.swing.JCheckBox p6r6;
    private javax.swing.JLabel p7;
    // End of variables declaration//GEN-END:variables
    private Object ax = System.getenv("username");
    private String usuario = String.valueOf(ax);
    private PlaceHolder holder;

    int contador=0;
    int c1=0;
    int c2=0;
    int c3=0;
    int c4=0;
    int c5=0;
    int c6=0;
    int c7=0;
    int ev1=0;
    int ev2=0;
    int ev3=0;
    int ev4=0;
    int ev5=0;
    int ev6=0;
    int ev7=0;
    int sumcres=0;
    String r1,r2,r3,r4,r5,r6,r7,sector,personal,cargo;
    Timer timer;
   
    
    
    
    public void cargarEncuesta() throws SQLException{
        p1r1.setVisible(false);
        p1r2.setVisible(false);
        p1r3.setVisible(false);
        p1r4.setVisible(false);
        p1r5.setVisible(false);
        p1r6.setVisible(false);
        
        p2r1.setVisible(false);
        p2r2.setVisible(false);
        p2r3.setVisible(false);
        p2r4.setVisible(false);
        p2r5.setVisible(false);
        p2r6.setVisible(false);
        
        p3r1.setVisible(false);
        p3r2.setVisible(false);
        p3r3.setVisible(false);
        p3r4.setVisible(false);
        p3r5.setVisible(false);
        p3r6.setVisible(false);
        
        p4r1.setVisible(false);
        p4r2.setVisible(false);
        p4r3.setVisible(false);
        p4r4.setVisible(false);
        p4r5.setVisible(false);
        p4r6.setVisible(false);
        
        p5r1.setVisible(false);
        p5r2.setVisible(false);
        p5r3.setVisible(false);
        p5r4.setVisible(false);
        p5r5.setVisible(false);
        p5r6.setVisible(false);
        
        p6r1.setVisible(false);
        p6r2.setVisible(false);
        p6r3.setVisible(false);
        p6r4.setVisible(false);
        p6r5.setVisible(false);
        p6r6.setVisible(false);
        
        p7.setVisible(false);
        comentario.setVisible(false);
       
         Statement std = conexion.ConnectDB().createStatement();
       
         
         ResultSet rs1 =std.executeQuery("SELECT Sector,Personal,Cargo FROM nomina where user_win='"+usuario+"' ");
        
        if(rs1.next()){     
           
          sector=rs1.getString("Sector");
          personal=rs1.getString("Personal");
          cargo=rs1.getString("Cargo");
          
         // JOptionPane.showMessageDialog(null, "yo soy de "+sector);
            
        }
        
         ResultSet rs11 =std.executeQuery("SELECT nombre_enc FROM preguntas_enc where Sector='"+sector+"' ");
        
        if(rs11.next()){     
           
          name.setText(rs11.getString("nombre_enc"));
         
            
        }
  
        ResultSet rss =std.executeQuery("SELECT * FROM preguntas_enc where Sector='"+sector+"'   ");
        
       if(rss.next()==false){
          // JOptionPane.showMessageDialog(null, "no existe encuesta para ti");
       ventanaClose();
         
       }else{
             ResultSet rs =std.executeQuery("SELECT * FROM respuestas_enc where User_Win='"+usuario+"' AND Cargo='"+cargo+"' AND Sector='"+sector+"'  ");
        
        if(rs.next()==true){      
        // JOptionPane.showMessageDialog(null, "ya resolviste esta encuesta");    
        ventanaClose();
         
        }
          
       }
     

       
         ResultSet rs2 =std.executeQuery("SELECT pregunta,r1,r2,r3,r4,r5,r6 FROM preguntas_enc where id_pregunta='1' AND Sector='"+sector+"'  ");

         
          if(rs2.next()){
            if(rs2.getString("pregunta").equals("")){
            }
            else{
                p1.setText("<html>"+rs2.getString("pregunta"));
              contador++;
              ev1=1;
            }
            if(rs2.getString("r1").equals("")){
            } else {
              p1r1.setVisible(true);
              p1r1.setText(rs2.getString("r1"));
            }
             if(rs2.getString("r2").equals("")){
            } else {
              p1r2.setVisible(true);
              p1r2.setText(rs2.getString("r2"));
            }
              if(rs2.getString("r3").equals("")){
            } else {
              p1r3.setVisible(true);
              p1r3.setText(rs2.getString("r3"));
            }
               if(rs2.getString("r4").equals("")){
            } else {
              p1r4.setVisible(true);
              p1r4.setText(rs2.getString("r4"));
            }
                if(rs2.getString("r5").equals("")){
            } else {
              p1r5.setVisible(true);
              p1r5.setText(rs2.getString("r5"));
            }
                if(rs2.getString("r6").equals("")){
            } else {
              p1r6.setVisible(true);
              p1r6.setText(rs2.getString("r6"));
            }

    
            
        }
        
        ResultSet rs3 =std.executeQuery("SELECT pregunta,r1,r2,r3,r4,r5,r6 FROM preguntas_enc where id_pregunta='2' AND Sector='"+sector+"'  ");
        if(rs3.next()){     
            if(rs3.getString("pregunta").equals("")){
            }
            else{
                p2.setText("<html>"+rs3.getString("pregunta"));
              contador++;
              ev2=1;
            }
             if(rs3.getString("r1").equals("")){
            } else {
              p2r1.setVisible(true);
              p2r1.setText(rs3.getString("r1"));
            }
             if(rs3.getString("r2").equals("")){
            } else {
              p2r2.setVisible(true);
              p2r2.setText(rs3.getString("r2"));
            }
              if(rs3.getString("r3").equals("")){
            } else {
              p2r3.setVisible(true);
              p2r3.setText(rs3.getString("r3"));
            }
               if(rs3.getString("r4").equals("")){
            } else {
              p2r4.setVisible(true);
              p2r4.setText(rs3.getString("r4"));
            }
                if(rs3.getString("r5").equals("")){
            } else {
              p2r5.setVisible(true);
              p2r5.setText(rs3.getString("r5"));
            }
                if(rs3.getString("r6").equals("")){
            } else {
              p2r6.setVisible(true);
              p2r6.setText(rs3.getString("r6"));
            }
            
            
        }
        
        ResultSet rs4 =std.executeQuery("SELECT pregunta,r1,r2,r3,r4,r5,r6 FROM preguntas_enc where id_pregunta='3' AND Sector='"+sector+"'   ");
        if(rs4.next()){     
            if(rs4.getString("pregunta").equals("")){
            }
            else{
             p3.setText("<html>"+rs4.getString("pregunta"));
              contador++;
              ev3=1;
            }
             if(rs4.getString("r1").equals("")){
            } else {
              p3r1.setVisible(true);
              p3r1.setText(rs4.getString("r1"));
            }
             if(rs4.getString("r2").equals("")){
            } else {
              p3r2.setVisible(true);
              p3r2.setText(rs4.getString("r2"));
            }
              if(rs4.getString("r3").equals("")){
            } else {
              p3r3.setVisible(true);
              p3r3.setText(rs4.getString("r3"));
            }
               if(rs4.getString("r4").equals("")){
            } else {
              p3r4.setVisible(true);
              p3r4.setText(rs4.getString("r4"));
            }
                if(rs4.getString("r5").equals("")){
            } else {
              p3r5.setVisible(true);
              p3r5.setText(rs4.getString("r5"));
            }
                if(rs4.getString("r6").equals("")){
            } else {
              p3r6.setVisible(true);
              p3r6.setText(rs4.getString("r6"));
            }
            
            
        }
        
        ResultSet rs5 =std.executeQuery("SELECT pregunta,r1,r2,r3,r4,r5,r6 FROM preguntas_enc where id_pregunta='4' AND Sector='"+sector+"'   ");
        if(rs5.next()){     
            if(rs5.getString("pregunta").equals("")){
            }
            else{
             p4.setText("<html>"+rs5.getString("pregunta"));
              contador++;
              ev5=1;
            }
             if(rs5.getString("r1").equals("")){
            } else {
              p4r1.setVisible(true);
              p4r1.setText(rs5.getString("r1"));
            }
             if(rs5.getString("r2").equals("")){
            } else {
              p4r2.setVisible(true);
              p4r2.setText(rs5.getString("r2"));
            }
              if(rs5.getString("r3").equals("")){
            } else {
              p4r3.setVisible(true);
              p4r3.setText(rs5.getString("r3"));
            }
               if(rs5.getString("r4").equals("")){
            } else {
              p4r4.setVisible(true);
              p4r4.setText(rs5.getString("r4"));
            }
                if(rs5.getString("r5").equals("")){
            } else {
              p4r5.setVisible(true);
              p4r5.setText(rs5.getString("r5"));
            }
                if(rs5.getString("r6").equals("")){
            } else {
              p4r6.setVisible(true);
              p4r6.setText(rs5.getString("r6"));
            }
            
            
        }
        
        ResultSet rs6 =std.executeQuery("SELECT pregunta,r1,r2,r3,r4,r5,r6 FROM preguntas_enc where id_pregunta='5' AND Sector='"+sector+"'   ");
        if(rs6.next()){     
            if(rs6.getString("pregunta").equals("")){
            }
            else{
             p5.setText("<html>"+rs6.getString("pregunta"));
              contador++;
              ev6=1;
            }
             if(rs6.getString("r1").equals("")){
            } else {
              p5r1.setVisible(true);
              p5r1.setText(rs6.getString("r1"));
            }
             if(rs6.getString("r2").equals("")){
            } else {
              p5r2.setVisible(true);
              p5r2.setText(rs6.getString("r2"));
            }
              if(rs6.getString("r3").equals("")){
            } else {
              p5r3.setVisible(true);
              p5r3.setText(rs6.getString("r3"));
            }
               if(rs6.getString("r4").equals("")){
            } else {
              p5r4.setVisible(true);
              p5r4.setText(rs6.getString("r4"));
            }
                if(rs6.getString("r5").equals("")){
            } else {
              p5r5.setVisible(true);
              p5r5.setText(rs6.getString("r5"));
            }
                if(rs6.getString("r6").equals("")){
            } else {
              p5r6.setVisible(true);
              p5r6.setText(rs6.getString("r6"));
            }
            
            
        }
        
         ResultSet rs7 =std.executeQuery("SELECT pregunta,r1,r2,r3,r4,r5,r6 FROM preguntas_enc where id_pregunta='6'  AND Sector='"+sector+"'  ");
        if(rs7.next()){     
            if(rs7.getString("pregunta").equals("")){
            }
            else{
             p6.setText("<html>"+rs7.getString("pregunta"));
              contador++;
              ev7=1;
            }
             if(rs7.getString("r1").equals("")){
            } else {
              p6r1.setVisible(true);
              p6r1.setText(rs7.getString("r1"));
            }
             if(rs7.getString("r2").equals("")){
            } else {
              p6r2.setVisible(true);
              p6r2.setText(rs7.getString("r2"));
            }
              if(rs7.getString("r3").equals("")){
            } else {
              p6r3.setVisible(true);
              p6r3.setText(rs7.getString("r3"));
            }
               if(rs7.getString("r4").equals("")){
            } else {
              p6r4.setVisible(true);
              p6r4.setText(rs7.getString("r4"));
            }
                if(rs7.getString("r5").equals("")){
            } else {
              p6r5.setVisible(true);
              p6r5.setText(rs7.getString("r5"));
            }
                if(rs7.getString("r6").equals("")){
            } else {
              p6r6.setVisible(true);
              p6r6.setText(rs7.getString("r6"));
            }
            
            
        }
 
        ResultSet rs8 =std.executeQuery("SELECT pregunta FROM preguntas_enc where id_pregunta='7' AND Sector='"+sector+"'   ");
        if(rs8.next()){     
           p7.setVisible(true);
           holder = new PlaceHolder(comentario, "Maximo 200 caracteres ");
           comentario.setVisible(true);
            contador++;
             ev4=1;
        }
        else{
           
        }
         //JOptionPane.showMessageDialog(null,"total de preguntas  :"+contador);
         if ((ev1==1 && ev2==1 && ev3==1&& ev4==1&& ev5==1&& ev6==1&& ev7==1)||(ev1==1 && ev2==1 && ev3==1&&  ev5==1&& ev6==1&& ev7==1) ){     
         }
         else if( (ev1==1 && ev2==1 && ev3==1&& ev4==1  )|| (ev1==1 && ev2==1 )){
             setBounds(0,0,770,700);
             setLocationRelativeTo(null);
             getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,770,700));
             jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 7, 198, 50));
             
         }
        
    }
  public void ventanaClose(){
      
                 timer = new Timer(600,new ActionListener() {
                int n=0;
          public void actionPerformed(ActionEvent e) {
              n++;
              
              if(n==1){
             
                   dispose();
                   timer.stop();
                   
              }
          }
      });
       timer.start();
                            
                
  }

}
